import { IAttack } from "../../../entity/attack";
import { PokeType } from "../../../entity/type";

export const allAttackMap: { [key: number]: IAttack } = {
  1: {
    id: 1,
    name: "あわ",
    type: PokeType.water,
    raidValue: 12,
    trainerValue: 7,
  },
  2: {
    id: 2,
    name: "いわくだき",
    type: PokeType.rock,
    raidValue: 15,
    trainerValue: 9,
  },
  3: {
    id: 3,
    name: "サイコカッター",
    type: PokeType.psychic,
    raidValue: 5,
    trainerValue: 3,
  },
  4: {
    id: 4,
    name: "ねんりき",
    type: PokeType.psychic,
    raidValue: 20,
    trainerValue: 16,
  },
  5: {
    id: 5,
    name: "うちおとす",
    type: PokeType.rock,
    raidValue: 16,
    trainerValue: 12,
  },
  6: {
    id: 6,
    name: "アイアンテール",
    type: PokeType.steel,
    raidValue: 15,
    trainerValue: 9,
  },
  7: {
    id: 7,
    name: "たきのぼり",
    type: PokeType.water,
    raidValue: 16,
    trainerValue: 12,
  },
  8: {
    id: 8,
    name: "マッドショット",
    type: PokeType.ground,
    raidValue: 5,
    trainerValue: 3,
  },
  9: {
    id: 9,
    name: "ドラゴンテール",
    type: PokeType.dragon,
    raidValue: 15,
    trainerValue: 13,
  },
  10: {
    id: 10,
    name: "りゅうのいぶき",
    type: PokeType.dragon,
    raidValue: 6,
    trainerValue: 4,
  },
  11: {
    id: 11,
    name: "メタルクロー",
    type: PokeType.steel,
    raidValue: 8,
    trainerValue: 5,
  },
  12: {
    id: 12,
    name: "つつく",
    type: PokeType.flying,
    raidValue: 10,
    trainerValue: 6,
  },
  1000: {
    id: 1000,
    name: "じゃれつく",
    type: PokeType.fairy,
    raidValue: 90,
    trainerValue: 90,
  },
  1001: {
    id: 1001,
    name: "ハイドロポンプ",
    type: PokeType.water,
    raidValue: 130,
    trainerValue: 130,
  },
  1002: {
    id: 1002,
    name: "れいとうビーム",
    type: PokeType.ice,
    raidValue: 90,
    trainerValue: 90,
  },
  1003: {
    id: 1003,
    name: "サイコキネシス",
    type: PokeType.psychic,
    raidValue: 90,
    trainerValue: 90,
  },
  1004: {
    id: 1004,
    name: "きあいだま",
    type: PokeType.fighting,
    raidValue: 140,
    trainerValue: 150,
  },
  1005: {
    id: 1005,
    name: "10まんボルト",
    type: PokeType.electric,
    raidValue: 80,
    trainerValue: 90,
  },
  1006: {
    id: 1006,
    name: "かえんほうしゃ",
    type: PokeType.fire,
    raidValue: 70,
    trainerValue: 90,
  },
  1007: {
    id: 1007,
    name: "ストーンエッジ",
    type: PokeType.rock,
    raidValue: 100,
    trainerValue: 100,
  },
  1008: {
    id: 1008,
    name: "ラスターカノン",
    type: PokeType.steel,
    raidValue: 100,
    trainerValue: 110,
  },
  1009: {
    id: 1009,
    name: "ふぶき",
    type: PokeType.ice,
    raidValue: 130,
    trainerValue: 140,
  },
  1010: {
    id: 1010,
    name: "かみなり",
    type: PokeType.electric,
    raidValue: 100,
    trainerValue: 100,
  },
  1011: {
    id: 1011,
    name: "なみのり",
    type: PokeType.water,
    raidValue: 65,
    trainerValue: 65,
  },
  1012: {
    id: 1012,
    name: "じしん",
    type: PokeType.ground,
    raidValue: 140,
    trainerValue: 120,
  },
  1013: {
    id: 1013,
    name: "だいもんじ",
    type: PokeType.fire,
    raidValue: 140,
    trainerValue: 140,
  },
  1014: {
    id: 1014,
    name: "ソーラービーム",
    type: PokeType.grass,
    raidValue: 180,
    trainerValue: 150,
  },
  1015: {
    id: 1015,
    name: "ほのおのパンチ",
    type: PokeType.fire,
    raidValue: 55,
    trainerValue: 55,
  },
  1016: {
    id: 1016,
    name: "りゅうせいぐん",
    type: PokeType.dragon,
    raidValue: 150,
    trainerValue: 150,
  },
  1017: {
    id: 1017,
    name: "アイアンヘッド",
    type: PokeType.steel,
    raidValue: 60,
    trainerValue: 70,
  },
  1018: {
    id: 1018,
    name: "ゴッドバード",
    type: PokeType.flying,
    raidValue: 80,
    trainerValue: 75,
  },
  1019: {
    id: 1019,
    name: "マジカルシャイン",
    type: PokeType.fairy,
    raidValue: 100,
    trainerValue: 110,
  },
  1020: {
    id: 1020,
    name: "りゅうのはどう",
    type: PokeType.dragon,
    raidValue: 90,
    trainerValue: 90,
  },
  1021: {
    id: 1021,
    name: "ムーンフォース",
    type: PokeType.fairy,
    raidValue: 130,
    trainerValue: 110,
  },
};
