import { IAttack } from "../../../entity/attack";
import { PokeType } from "../../../entity/type";

export const allAttackMap: { [key: number]: IAttack } = {
  1: {
    id: 1,
    name: "あわ",
    type: PokeType.water,
    raidValue: 12,
    trainerValue: 7,
    energy: 11,
  },
  2: {
    id: 2,
    name: "いわくだき",
    type: PokeType.rock,
    raidValue: 15,
    trainerValue: 9,
    energy: 7,
  },
  3: {
    id: 3,
    name: "サイコカッター",
    type: PokeType.psychic,
    raidValue: 5,
    trainerValue: 3,
    energy: 9,
  },
  4: {
    id: 4,
    name: "ねんりき",
    type: PokeType.psychic,
    raidValue: 20,
    trainerValue: 16,
    energy: 12,
  },
  5: {
    id: 5,
    name: "うちおとす",
    type: PokeType.rock,
    raidValue: 16,
    trainerValue: 12,
    energy: 8,
  },
  6: {
    id: 6,
    name: "アイアンテール",
    type: PokeType.steel,
    raidValue: 15,
    trainerValue: 9,
    energy: 6,
  },
  7: {
    id: 7,
    name: "たきのぼり",
    type: PokeType.water,
    raidValue: 16,
    trainerValue: 12,
    energy: 8,
  },
  8: {
    id: 8,
    name: "マッドショット",
    type: PokeType.ground,
    raidValue: 5,
    trainerValue: 3,
    energy: 9,
  },
  9: {
    id: 9,
    name: "ドラゴンテール",
    type: PokeType.dragon,
    raidValue: 15,
    trainerValue: 13,
    energy: 9,
  },
  10: {
    id: 10,
    name: "りゅうのいぶき",
    type: PokeType.dragon,
    raidValue: 6,
    trainerValue: 4,
    energy: 3,
  },
  11: {
    id: 11,
    name: "メタルクロー",
    type: PokeType.steel,
    raidValue: 8,
    trainerValue: 5,
    energy: 6,
  },
  12: {
    id: 12,
    name: "つつく",
    type: PokeType.flying,
    raidValue: 10,
    trainerValue: 6,
    energy: 5,
  },
  13: {
    id: 13,
    name: "はっぱカッター",
    type: PokeType.grass,
    raidValue: 13,
    trainerValue: 10,
    energy: 4,
  },
  14: {
    id: 14,
    name: "つるのムチ",
    type: PokeType.grass,
    raidValue: 7,
    trainerValue: 5,
    energy: 8,
  },
  15: {
    id: 15,
    name: "シャドークロー",
    type: PokeType.ghost,
    raidValue: 9,
    trainerValue: 6,
    energy: 8,
  },
  16: {
    id: 16,
    name: "だましうち",
    type: PokeType.dark,
    raidValue: 10,
    trainerValue: 6,
    energy: 6,
  },
  17: {
    id: 17,
    name: "エアスラッシュ",
    type: PokeType.flying,
    raidValue: 14,
    trainerValue: 9,
    energy: 9,
  },
  18: {
    id: 18,
    name: "バークアウト",
    type: PokeType.dark,
    raidValue: 12,
    trainerValue: 5,
    energy: 13,
  },
  19: {
    id: 19,
    name: "でんこうせっか",
    type: PokeType.normal,
    raidValue: 8,
    trainerValue: 5,
    energy: 8,
  },
  20: {
    id: 20,
    name: "ほのおのキバ",
    type: PokeType.fire,
    raidValue: 12,
    trainerValue: 8,
    energy: 5,
  },
  21: {
    id: 21,
    name: "かみつく",
    type: PokeType.dark,
    raidValue: 6,
    trainerValue: 4,
    energy: 2,
  },
  22: {
    id: 22,
    name: "チャージビーム",
    type: PokeType.electric,
    raidValue: 8,
    trainerValue: 5,
    energy: 11,
  },
  23: {
    id: 23,
    name: "じんつうりき",
    type: PokeType.psychic,
    raidValue: 12,
    trainerValue: 8,
    energy: 10,
  },
  24: {
    id: 24,
    name: "あまえる",
    type: PokeType.fairy,
    raidValue: 20,
    trainerValue: 15,
    energy: 6,
  },
  25: {
    id: 25,
    name: "みずでっぽう",
    type: PokeType.water,
    raidValue: 5,
    trainerValue: 3,
    energy: 3,
  },
  26: {
    id: 26,
    name: "はがねのつばさ",
    type: PokeType.steel,
    raidValue: 11,
    trainerValue: 7,
    energy: 5,
  },
  27: {
    id: 27,
    name: "めざめるパワー",
    type: PokeType.normal,
    raidValue: 15,
    trainerValue: 9,
    energy: 8,
  },
  28: {
    id: 28,
    name: "やきつくす",
    type: PokeType.fire,
    raidValue: 29,
    trainerValue: 15,
    energy: 20,
  },
  1000: {
    id: 1000,
    name: "じゃれつく",
    type: PokeType.fairy,
    raidValue: 90,
    trainerValue: 90,
    energy: 60,
  },
  1001: {
    id: 1001,
    name: "ハイドロポンプ",
    type: PokeType.water,
    raidValue: 130,
    trainerValue: 130,
    energy: 75,
  },
  1002: {
    id: 1002,
    name: "れいとうビーム",
    type: PokeType.ice,
    raidValue: 90,
    trainerValue: 90,
    energy: 55,
  },
  1003: {
    id: 1003,
    name: "サイコキネシス",
    type: PokeType.psychic,
    raidValue: 90,
    trainerValue: 90,
    energy: 55,
  },
  1004: {
    id: 1004,
    name: "きあいだま",
    type: PokeType.fighting,
    raidValue: 140,
    trainerValue: 150,
    energy: 75,
  },
  1005: {
    id: 1005,
    name: "10まんボルト",
    type: PokeType.electric,
    raidValue: 80,
    trainerValue: 90,
    energy: 55,
  },
  1006: {
    id: 1006,
    name: "かえんほうしゃ",
    type: PokeType.fire,
    raidValue: 70,
    trainerValue: 90,
    energy: 55,
  },
  1007: {
    id: 1007,
    name: "ストーンエッジ",
    type: PokeType.rock,
    raidValue: 100,
    trainerValue: 100,
    energy: 55,
  },
  1008: {
    id: 1008,
    name: "ラスターカノン",
    type: PokeType.steel,
    raidValue: 100,
    trainerValue: 110,
    energy: 70,
  },
  1009: {
    id: 1009,
    name: "ふぶき",
    type: PokeType.ice,
    raidValue: 130,
    trainerValue: 140,
    energy: 75,
  },
  1010: {
    id: 1010,
    name: "かみなり",
    type: PokeType.electric,
    raidValue: 100,
    trainerValue: 100,
    energy: 60,
  },
  1011: {
    id: 1011,
    name: "なみのり",
    type: PokeType.water,
    raidValue: 65,
    trainerValue: 65,
    energy: 40,
  },
  1012: {
    id: 1012,
    name: "じしん",
    type: PokeType.ground,
    raidValue: 140,
    trainerValue: 120,
    energy: 65,
  },
  1013: {
    id: 1013,
    name: "だいもんじ",
    type: PokeType.fire,
    raidValue: 140,
    trainerValue: 140,
    energy: 80,
  },
  1014: {
    id: 1014,
    name: "ソーラービーム",
    type: PokeType.grass,
    raidValue: 180,
    trainerValue: 150,
    energy: 80,
  },
  1015: {
    id: 1015,
    name: "ほのおのパンチ",
    type: PokeType.fire,
    raidValue: 55,
    trainerValue: 55,
    energy: 40,
  },
  1016: {
    id: 1016,
    name: "りゅうせいぐん",
    type: PokeType.dragon,
    raidValue: 150,
    trainerValue: 150,
    energy: 65,
  },
  1017: {
    id: 1017,
    name: "アイアンヘッド",
    type: PokeType.steel,
    raidValue: 60,
    trainerValue: 70,
    energy: 50,
  },
  1018: {
    id: 1018,
    name: "ゴッドバード",
    type: PokeType.flying,
    raidValue: 80,
    trainerValue: 75,
    energy: 45,
  },
  1019: {
    id: 1019,
    name: "マジカルシャイン",
    type: PokeType.fairy,
    raidValue: 100,
    trainerValue: 110,
    energy: 70,
  },
  1020: {
    id: 1020,
    name: "りゅうのはどう",
    type: PokeType.dragon,
    raidValue: 90,
    trainerValue: 90,
    energy: 60,
  },
  1021: {
    id: 1021,
    name: "ムーンフォース",
    type: PokeType.fairy,
    raidValue: 130,
    trainerValue: 110,
    energy: 60,
  },
  1022: {
    id: 1022,
    name: "ヘドロばくだん",
    type: PokeType.poison,
    raidValue: 80,
    trainerValue: 80,
    energy: 50,
  },
  1023: {
    id: 1023,
    name: "はなふぶき",
    type: PokeType.grass,
    raidValue: 110,
    trainerValue: 110,
    energy: 65,
  },
  1024: {
    id: 1024,
    name: "ハードプラント",
    type: PokeType.grass,
    raidValue: 100,
    trainerValue: 100,
    energy: 45,
  },
  1025: {
    id: 1025,
    name: "パワージェム",
    type: PokeType.rock,
    raidValue: 80,
    trainerValue: 80,
    energy: 60,
  },
  1026: {
    id: 1026,
    name: "イカサマ",
    type: PokeType.dark,
    raidValue: 70,
    trainerValue: 70,
    energy: 45,
  },
  1027: {
    id: 1027,
    name: "かげうち",
    type: PokeType.ghost,
    raidValue: 50,
    trainerValue: 50,
    energy: 45,
  },
  1028: {
    id: 1028,
    name: "リーフブレード",
    type: PokeType.grass,
    raidValue: 70,
    trainerValue: 70,
    energy: 35,
  },
  1029: {
    id: 1029,
    name: "シザークロス",
    type: PokeType.bug,
    raidValue: 45,
    trainerValue: 45,
    energy: 35,
  },
  1030: {
    id: 1030,
    name: "つじぎり",
    type: PokeType.dark,
    raidValue: 50,
    trainerValue: 50,
    energy: 35,
  },
  1031: {
    id: 1031,
    name: "つばめがえし",
    type: PokeType.flying,
    raidValue: 55,
    trainerValue: 55,
    energy: 45,
  },
  1032: {
    id: 1032,
    name: "インファイト",
    type: PokeType.fighting,
    raidValue: 100,
    trainerValue: 100,
    energy: 45,
  },
  1033: {
    id: 1033,
    name: "ワイルドボルト",
    type: PokeType.electric,
    raidValue: 90,
    trainerValue: 100,
    energy: 45,
  },
  1034: {
    id: 1034,
    name: "あやしいかぜ",
    type: PokeType.ghost,
    raidValue: 50,
    trainerValue: 45,
    energy: 45,
  },
  1035: {
    id: 1035,
    name: "シャドーボール",
    type: PokeType.ghost,
    raidValue: 100,
    trainerValue: 100,
    energy: 55,
  },
  1036: {
    id: 1036,
    name: "シャドーダイブ",
    type: PokeType.ghost,
    raidValue: 140,
    trainerValue: 120,
    energy: 90,
  },
  1037: {
    id: 1037,
    name: "ドラゴンクロー",
    type: PokeType.dragon,
    raidValue: 50,
    trainerValue: 50,
    energy: 35,
  },
  1038: {
    id: 1038,
    name: "げんしのちから",
    type: PokeType.rock,
    raidValue: 70,
    trainerValue: 60,
    energy: 45,
  },
  1039: {
    id: 1039,
    name: "かみくだく",
    type: PokeType.dark,
    raidValue: 70,
    trainerValue: 70,
    energy: 45,
  },
  1040: {
    id: 1040,
    name: "げきりん",
    type: PokeType.dragon,
    raidValue: 110,
    trainerValue: 110,
    energy: 60,
  },
  1041: {
    id: 1041,
    name: "たつまき",
    type: PokeType.dragon,
    raidValue: 45,
    trainerValue: 45,
    energy: 45,
  },
  1042: {
    id: 1042,
    name: "おんがえし",
    type: PokeType.normal,
    raidValue: 35,
    trainerValue: 130,
    energy: 70,
  },
  1043: {
    id: 1043,
    name: "アクアテール",
    type: PokeType.water,
    raidValue: 50,
    trainerValue: 50,
    energy: 35,
  },
  1044: {
    id: 1044,
    name: "クロスサンダー",
    type: PokeType.electric,
    raidValue: 140,
    trainerValue: 90,
    energy: 45,
  },
  1045: {
    id: 1045,
    name: "オーバーヒート",
    type: PokeType.fire,
    raidValue: 160,
    trainerValue: 130,
    energy: 55,
  },
  1046: {
    id: 1046,
    name: "クロスフレイム",
    type: PokeType.fire,
    raidValue: 140,
    trainerValue: 90,
    energy: 45,
  },
  1047: {
    id: 1047,
    name: "じならし",
    type: PokeType.ground,
    raidValue: 80,
    trainerValue: 80,
    energy: 60,
  },
  1048: {
    id: 1048,
    name: "ばかぢから",
    type: PokeType.fighting,
    raidValue: 85,
    trainerValue: 85,
    energy: 40,
  },
  1049: {
    id: 1049,
    name: "シンクロノイズ",
    type: PokeType.psychic,
    raidValue: 80,
    trainerValue: 80,
    energy: 50,
  },
  1050: {
    id: 1050,
    name: "ヘドロウェーブ",
    type: PokeType.poison,
    raidValue: 110,
    trainerValue: 110,
    energy: 65,
  },
  1051: {
    id: 1051,
    name: "だくりゅう",
    type: PokeType.water,
    raidValue: 50,
    trainerValue: 35,
    energy: 35,
  },
  1052: {
    id: 1052,
    name: "ハイドロカノン",
    type: PokeType.water,
    raidValue: 90,
    trainerValue: 80,
    energy: 40,
  },
  1053: {
    id: 1053,
    name: "ブレイブバード",
    type: PokeType.flying,
    raidValue: 130,
    trainerValue: 130,
    energy: 55,
  },
  1054: {
    id: 1054,
    name: "せいなるほのお",
    type: PokeType.fire,
    raidValue: 120,
    trainerValue: 130,
    energy: 65,
  },
  1055: {
    id: 1055,
    name: "せいなるほのお+",
    type: PokeType.fire,
    raidValue: 135,
    trainerValue: 130,
    energy: 65,
  },
  1056: {
    id: 1056,
    name: "せいなるほのお++",
    type: PokeType.fire,
    raidValue: 155,
    trainerValue: 130,
    energy: 65,
  },
  1057: {
    id: 1057,
    name: "みらいよち",
    type: PokeType.psychic,
    raidValue: 120,
    trainerValue: 120,
    energy: 65,
  },
  1058: {
    id: 1058,
    name: "エアロブラスト",
    type: PokeType.flying,
    raidValue: 180,
    trainerValue: 170,
    energy: 75,
  },
  1059: {
    id: 1059,
    name: "エアロブラスト+",
    type: PokeType.flying,
    raidValue: 200,
    trainerValue: 170,
    energy: 75,
  },
  1060: {
    id: 1060,
    name: "エアロブラスト++",
    type: PokeType.flying,
    raidValue: 225,
    trainerValue: 170,
    energy: 75,
  },
  1061: {
    id: 1061,
    name: "だんがいのつるぎ",
    type: PokeType.flying,
    raidValue: 130,
    trainerValue: 130,
    energy: 60,
  },
  1062: {
    id: 1062,
    name: "こんげんのはどう",
    type: PokeType.water,
    raidValue: 130,
    trainerValue: 130,
    energy: 60,
  },
};
const allAttackList = Object.keys(allAttackMap).map(
  (key) => allAttackMap[Number(key)]
);
export const allFastAttacks = allAttackList.filter(
  (attack) => attack.id < 1000
);
export const allChargedAttacks = allAttackList.filter(
  (attack) => attack.id >= 1000
);
