const effective = 1.6;
const noEffective = 0.625;

export const effectiveData: { [key: number]: { [key: number]: number } } = {
  1: {
    6: noEffective,
    9: noEffective,
    8: noEffective * noEffective,
  },
  2: {
    1: effective,
    6: effective,
    9: effective,
    15: effective,
    17: effective,
    3: noEffective,
    4: noEffective,
    7: noEffective,
    14: noEffective,
    18: noEffective,
  },
  3: {
    2: effective,
    7: effective,
    12: effective,
    6: noEffective,
    9: noEffective,
    13: noEffective,
  },
  4: {
    12: effective,
    18: effective,
    3: noEffective,
    5: noEffective,
    6: noEffective,
    8: noEffective,
  },
  5: {
    4: effective,
    10: effective,
    13: effective,
    6: effective,
    9: effective,
    7: noEffective,
    12: noEffective,
    3: noEffective * noEffective,
  },
  6: {
    3: effective,
    7: effective,
    10: effective,
    15: effective,
    2: noEffective,
    5: noEffective,
    9: noEffective,
  },
  7: {
    12: effective,
    14: effective,
    17: effective,
    2: noEffective,
    3: noEffective,
    4: noEffective,
    8: noEffective,
    9: noEffective,
    10: noEffective,
    18: noEffective,
  },
  8: {
    8: effective,
    14: effective,
    17: noEffective,
    1: noEffective * noEffective,
  },
  9: {
    6: effective,
    15: effective,
    18: effective,
    9: noEffective,
    10: noEffective,
    11: noEffective,
    13: noEffective,
  },
  10: {
    7: effective,
    9: effective,
    12: effective,
    15: effective,
    6: noEffective,
    10: noEffective,
    11: noEffective,
    16: noEffective,
  },
  11: {
    5: effective,
    6: effective,
    10: effective,
    11: noEffective,
    12: noEffective,
    16: noEffective,
  },
  12: {
    5: effective,
    6: effective,
    11: effective,
    3: noEffective,
    4: noEffective,
    7: noEffective,
    9: noEffective,
    10: noEffective,
    12: noEffective,
    16: noEffective,
  },
  13: {
    3: effective,
    11: effective,
    12: noEffective,
    13: noEffective,
    16: noEffective,
    5: noEffective * noEffective,
  },
  14: {
    2: effective,
    4: effective,
    9: noEffective,
    14: noEffective,
    17: noEffective * noEffective,
  },
  15: {
    3: effective,
    5: effective,
    12: effective,
    16: effective,
    9: noEffective,
    10: noEffective,
    11: noEffective,
    15: noEffective,
  },
  16: {
    16: effective,
    9: noEffective,
    18: noEffective * noEffective,
  },
  17: {
    8: effective,
    14: effective,
    2: noEffective,
    17: noEffective,
    18: noEffective,
  },
  18: {
    2: effective,
    16: effective,
    17: effective,
    4: noEffective,
    9: noEffective,
    10: noEffective,
  },
};
