import { IPokemon } from "../../../entity/pokemon";
import { PokeType } from "../../../entity/type";

export const allPokemons: IPokemon[] = [
  {
    id: "150",
    name: "ミュウツー",
    type1: PokeType.psychic,
    type2: PokeType.empty,
    attack: 300,
    defence: 182,
    hp: 214,
    fastAttacks: [3, 4],
    chargedAttacks: [1003, 1004, 1005, 1006, 1002],
  },
  {
    id: "184",
    name: "マリルリ",
    type1: PokeType.water,
    type2: PokeType.fairy,
    attack: 112,
    defence: 152,
    hp: 225,
    fastAttacks: [1, 2],
    chargedAttacks: [1000, 1001, 1002],
  },
  {
    id: "382",
    name: "カイオーガ",
    type1: PokeType.water,
    type2: PokeType.empty,
    attack: 270,
    defence: 228,
    hp: 205,
    fastAttacks: [],
    chargedAttacks: [],
  },
  {
    id: "383",
    name: "グラードン",
    type1: PokeType.ground,
    type2: PokeType.empty,
    attack: 270,
    defence: 228,
    hp: 205,
    fastAttacks: [],
    chargedAttacks: [],
  },
  {
    id: "483",
    name: "ディアルガ",
    type1: PokeType.dragon,
    type2: PokeType.steel,
    attack: 275,
    defence: 211,
    hp: 205,
    fastAttacks: [],
    chargedAttacks: [],
  },
];
